use_frameworks!

pod 'Alamofire', '~> 3.4' 
pod "ABCustomUINavigationController"
pod "AFViewShaker", "~> 0.0.2"
pod "MLPAutoCompleteTextField"
pod "TSMessages"
pod 'ActionSheetPicker-3.0'
pod 'Toast', '~> 3.0'

